/**
 * Ingestion Domain Types, Canonical Event Taxonomy, and Constants
 */

export const EVENT_TYPES = {
  // Financial Events
  EARNINGS_RELEASE: 'EARNINGS_RELEASE',
  ANNUAL_REPORT: 'ANNUAL_REPORT',
  QUARTERLY_REPORT: 'QUARTERLY_REPORT',
  REVENUE_CHANGE: 'REVENUE_CHANGE',
  EARNINGS_CHANGE: 'EARNINGS_CHANGE',
  MARGIN_CHANGE: 'MARGIN_CHANGE',
  CASH_FLOW_CHANGE: 'CASH_FLOW_CHANGE',
  DEBT_CHANGE: 'DEBT_CHANGE',
  CAPEX_CHANGE: 'CAPEX_CHANGE',
  GUIDANCE_CHANGE: 'GUIDANCE_CHANGE',

  // Corporate Actions
  ACQUISITION: 'ACQUISITION',
  DIVESTITURE: 'DIVESTITURE',
  MERGER: 'MERGER',
  SPINOFF: 'SPINOFF',
  BUYBACK: 'BUYBACK',
  DIVIDEND_CHANGE: 'DIVIDEND_CHANGE',
  STOCK_SPLIT: 'STOCK_SPLIT',
  SHARE_ISSUANCE: 'SHARE_ISSUANCE',
  DEBT_ISSUANCE: 'DEBT_ISSUANCE',
  DEBT_REPAYMENT: 'DEBT_REPAYMENT',

  // Management / Governance
  CEO_CHANGE: 'CEO_CHANGE',
  CFO_CHANGE: 'CFO_CHANGE',
  EXECUTIVE_CHANGE: 'EXECUTIVE_CHANGE',
  BOARD_CHANGE: 'BOARD_CHANGE',
  GOVERNANCE_EVENT: 'GOVERNANCE_EVENT',

  // Regulatory / Legal
  REGULATORY_ACTION: 'REGULATORY_ACTION',
  LAWSUIT: 'LAWSUIT',
  INVESTIGATION: 'INVESTIGATION',
  ACCOUNTING_RESTATEMENT: 'ACCOUNTING_RESTATEMENT',
  SECURITY_FRAUD_EVENT: 'SECURITY_FRAUD_EVENT',

  // Market Events
  PRICE_MOVE: 'PRICE_MOVE',
  VOLUME_SPIKE: 'VOLUME_SPIKE',
  VOLATILITY_SPIKE: 'VOLATILITY_SPIKE',
  FIFTY_TWO_WEEK_HIGH: '52W_HIGH',
  FIFTY_TWO_WEEK_LOW: '52W_LOW',

  // External / Macro
  MACRO_EVENT: 'MACRO_EVENT',
  SECTOR_EVENT: 'SECTOR_EVENT',
  COMPETITOR_EVENT: 'COMPETITOR_EVENT',
  SUPPLY_CHAIN_EVENT: 'SUPPLY_CHAIN_EVENT',
  GEOPOLITICAL_EVENT: 'GEOPOLITICAL_EVENT',

  // General News
  MATERIAL_NEWS: 'MATERIAL_NEWS',
  OTHER: 'OTHER',
  UNKNOWN: 'UNKNOWN'
};


export const SOURCE_TIERS = {
  TIER_1: 'TIER_1', // SEC filings, official IR press releases, regulatory notices
  TIER_2: 'TIER_2', // Reputable financial data providers, major news wires (Yahoo Finance, Bloomberg, Reuters)
  TIER_3: 'TIER_3', // Secondary news, analyst commentary
  TIER_4: 'TIER_4'  // Social media, unverified web forums
};

export const VALIDATION_STATUS = {
  VALIDATED: 'VALIDATED',
  PARTIALLY_VALIDATED: 'PARTIALLY_VALIDATED',
  REJECTED: 'REJECTED',
  UNAVAILABLE: 'UNAVAILABLE'
};

export const INGESTION_STAGES = {
  DISCOVERED: 'DISCOVERED',
  RETRIEVED: 'RETRIEVED',
  VALIDATED: 'VALIDATED',
  NORMALIZED: 'NORMALIZED',
  DEDUPLICATED: 'DEDUPLICATED',
  IMPACT_ANALYZED: 'IMPACT_ANALYZED',
  TRUTH_UPDATE_PENDING: 'TRUTH_UPDATE_PENDING',
  SNAPSHOT_CREATED: 'SNAPSHOT_CREATED',
  CHANGE_ANALYZED: 'CHANGE_ANALYZED',
  ALERT_EVALUATED: 'ALERT_EVALUATED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED'
};

export const GUIDANCE_DIRECTIONS = {
  RAISE: 'RAISE',
  MAINTAIN: 'MAINTAIN',
  LOWER: 'LOWER',
  WITHDRAWN: 'WITHDRAWN',
  NEW: 'NEW',
  UNAVAILABLE: 'UNAVAILABLE'
};
