import { spawnSync } from 'child_process';
import path from 'path';

const testSuites = [
  { name: 'Phase 1 Truth Layer', file: 'truthLayerTests.js' },
  { name: 'Phase 2A Valuation Engine', file: 'valuationPhase2ATests.js' },
  { name: 'Phase 2B Relative Valuation', file: 'valuationPhase2BTests.js' },
  { name: 'Phase 2B Numerical Integrity Audit', file: 'phase2bNumericalAudit.js' },
  { name: 'Phase 3 Risk Intelligence', file: 'phase3RiskTests.js' },
  { name: 'Phase 3 Portfolio Engine', file: 'phase3PortfolioTests.js' },
  { name: 'Phase 3 Decision Engine', file: 'phase3DecisionTests.js' },
  { name: 'Phase 3 Hostile Numerical Audit', file: 'phase3HostileAudit.js' },
  { name: 'Phase 4 Research Intelligence', file: 'phase4ResearchTests.js' },
  { name: 'Phase 4 Behavioral Audit', file: 'phase4HostileAudit.js' },
  { name: 'Phase 4 Comprehensive AI Hostile Suite', file: 'phase4AIHostileAudit.js' },
  { name: 'Phase 5 Persistent Workspace & Snapshots', file: 'phase5WorkspaceTests.js' },
  { name: 'Phase 5 Change & Drift Engine', file: 'phase5ChangeTests.js' },
  { name: 'Phase 5 Temporal & AI Hostile Audit', file: 'phase5HostileAudit.js' },
  { name: 'Phase 6 Automated Ingestion & Event Detection', file: 'phase6IngestionTests.js' },
  { name: 'Phase 6 Hostile Ingestion & Red-Team Audit', file: 'phase6HostileAudit.js' },
  { name: 'Phase 6 Production Reality Audit', file: 'phase6ProductionRealityAudit.js' },
  { name: 'Phase 7 Attention Intelligence', file: 'phase7AttentionTests.js' },
  { name: 'Phase 7 Portfolio Intelligence & Exposure', file: 'phase7PortfolioIntelligenceTests.js' },
  { name: 'Phase 7 Decision Operations & Reviews', file: 'phase7OperationsTests.js' },
  { name: 'Phase 7 Hostile Red-Team Audit (Attacks A-AI)', file: 'phase7HostileAudit.js' },
  { name: 'Phase 7 Production Reality Audit', file: 'phase7ProductionRealityAudit.js' },
  { name: 'Phase 7 Forensic Audit (Categories A-AZ)', file: 'phase7ComprehensiveHostileAuditAZ.js' },
  { name: 'Phase 8 Investor Copilot Core Suite', file: 'phase8CopilotTests.js' },
  { name: 'Phase 8 Workflow & Operations Suite', file: 'phase8WorkflowTests.js' },
  { name: 'Phase 8 Hostile Red-Team Audit (A to AZ)', file: 'phase8HostileAuditAZ.js' },
  { name: 'Phase 8 Mutation Testing Suite', file: 'phase8MutationTests.js' },
  { name: 'Phase 8 Production Reality Audit', file: 'phase8ProductionRealityAudit.js' },
  { name: 'Phase 9 Auth & RBAC Core Suite', file: 'phase9AuthRbacTests.js' },
  { name: 'Phase 9 Governance & Audit Suite', file: 'phase9GovernanceAuditTests.js' },
  { name: 'Phase 9 Job Infrastructure & Workers', file: 'phase9JobInfrastructureTests.js' },
  { name: 'Phase 9 Hostile Red-Team Audit (AAA to AAZ)', file: 'phase9HostileAuditAZ.js' },
  { name: 'Phase 9 Mutation Testing Suite', file: 'phase9MutationTests.js' },
  { name: 'Phase 9 Production Reality Audit', file: 'phase9ProductionRealityAudit.js' },
  { name: 'Phase 10 Source Registry & Capabilities', file: 'phase10SourceRegistryTests.js' },
  { name: 'Phase 10 Provider Adapters & Normalization', file: 'phase10ProviderAdapterTests.js' },
  { name: 'Phase 10 Data Lineage & Provenance Tracker', file: 'phase10DataLineageTests.js' },
  { name: 'Phase 10 Hostile Red-Team Audit (BAA to BBZ)', file: 'phase10HostileAuditAZ.js' },
  { name: 'Phase 10 Mutation Testing Suite', file: 'phase10MutationTests.js' },
  { name: 'Phase 10 Production Reality Audit', file: 'phase10ProductionRealityAudit.js' },
  { name: 'Phase 10 Live Provider Reality Audit', file: 'phase10LiveProviderRealityAudit.js' },
  { name: 'Phase 11 Fact Schema & Integrity', file: 'phase11FactSchemaTests.js' },
  { name: 'Phase 11 Accounting Consistency', file: 'phase11AccountingConsistencyTests.js' },
  { name: 'Phase 11 Restatement Engine', file: 'phase11RestatementTests.js' },
  { name: 'Phase 11 Data Quality & Scoring', file: 'phase11DataQualityTests.js' },
  { name: 'Phase 11 Hostile Red-Team Audit (CAA to CBD)', file: 'phase11HostileAuditAZ.js' },
  { name: 'Phase 11 Mutation Testing Suite', file: 'phase11MutationTests.js' },
  { name: 'Phase 11 Production Reality Audit', file: 'phase11ProductionRealityAudit.js' },
  { name: 'Phase 11 Live SEC Filing E2E Verification', file: 'phase11LiveSECE2EVerification.js' },
  { name: 'Phase 12 Portfolio Performance Core', file: 'phase12PerformanceCoreTests.js' },
  { name: 'Phase 12 Attribution, Brinson & Benchmark', file: 'phase12AttributionBrinsonTests.js' },
  { name: 'Phase 12 Decision Attribution & Thesis Tracking', file: 'phase12DecisionThesisTests.js' },
  { name: 'Phase 12 Multi-Currency & Drift Rebalancing', file: 'phase12MultiCurrencyDriftTests.js' },
  { name: 'Phase 12 Hostile Red-Team Audit (DAA to DBN)', file: 'phase12HostileAuditAZ.js' },
  { name: 'Phase 12 Mutation Testing Suite', file: 'phase12MutationTests.js' },
  { name: 'Phase 12 Production Reality HTTP Audit', file: 'phase12ProductionRealityAudit.js' },
  { name: 'Phase 12 Real Portfolio Validation', file: 'phase12RealPortfolioValidation.js' },
  { name: 'Phase 12 Final Reality & Methodology Audit', file: 'phase12FinalRealityAudit.js' },
  { name: 'Phase 13 Decision Snapshot Tests', file: 'phase13DecisionSnapshotTests.js' },
  { name: 'Phase 13 Forecast & Calibration Tests', file: 'phase13ForecastCalibrationTests.js' },
  { name: 'Phase 13 Thesis & Process Tests', file: 'phase13ThesisProcessTests.js' },
  { name: 'Phase 13 Decision Quality & Matrix Tests', file: 'phase13DecisionQualityMatrixTests.js' },
  { name: 'Phase 13 Hostile Audit (Attacks A-DM: 117 Categories)', file: 'phase13HostileAuditAtoDM.js' },
  { name: 'Phase 13 Temporal & Restatement Deep Tests', file: 'phase13TemporalRestatementDeepTests.js' },
  { name: 'Phase 13 Policy Hardening & Mathematical Integrity', file: 'phase13PolicyHardeningTests.js' },
  { name: 'Phase 13 Mutation Tests (25+ Mutations)', file: 'phase13MutationTests.js' },
  { name: 'Phase 13 Production Reality HTTP Audit', file: 'phase13ProductionRealityAudit.js' },
  { name: 'Phase 13 Real Ticker Validation', file: 'phase13RealTickerValidation.js' },
  { name: 'Phase 13 Golden E2E Trace', file: 'phase13GoldenE2ETest.js' },
  { name: 'Phase 14 Input & Expected Return Tests', file: 'phase14InputExpectedReturnTests.js' },
  { name: 'Phase 14 Covariance & Constraints Tests', file: 'phase14CovarianceConstraintTests.js' },
  { name: 'Phase 14 Optimization Methods & Execution Mechanics', file: 'phase14OptimizerMethodsTests.js' },
  { name: 'Phase 14 Scenarios, Stress & DAG Tests', file: 'phase14ScenarioStressTests.js' },
  { name: 'Phase 14 Hostile Red-Team Audit (154 Categories A-EX)', file: 'phase14HostileAuditAtoEX.js' },
  { name: 'Phase 14 Mutation Testing (25 Mutations)', file: 'phase14MutationTests.js' },
  { name: 'Phase 14 Production Reality HTTP Audit', file: 'phase14ProductionRealityAudit.js' },
  { name: 'Phase 14 Real Ticker Validation', file: 'phase14RealTickerValidation.js' },
  { name: 'Phase 14 Golden E2E Trace', file: 'phase14GoldenE2ETest.js' },
  { name: 'Phase 14 Policy Hardening, Determinism & Concurrency', file: 'phase14PolicyHardeningTests.js' },
  { name: 'Phase 14 Solver Convergence & Numerical Policy', file: 'phase14SolverConvergenceTests.js' },
  { name: 'Phase 14 Hostile Coverage & Category Reconciliation', file: 'phase14HostileCoverageReconciliationTests.js' },
  { name: 'Phase 15 Holdings Snapshot & Reconciliation', file: 'phase15HoldingsReconciliationTests.js' },
  { name: 'Phase 15 Drift & Constraint Monitoring', file: 'phase15DriftConstraintTests.js' },
  { name: 'Phase 15 Rebalance Trigger & Candidates', file: 'phase15RebalanceTriggerTests.js' },
  { name: 'Phase 15 Transaction Impact & Quality', file: 'phase15TransactionImpactQualityTests.js' },
  { name: 'Phase 15 Hostile Red-Team Audit (154 Categories A-EX)', file: 'phase15HostileAuditAtoEX.js' },
  { name: 'Phase 15 Mutation Testing (25 Mutations)', file: 'phase15MutationTests.js' },
  { name: 'Phase 15 Production Reality HTTP Audit', file: 'phase15ProductionRealityAudit.js' },
  { name: 'Phase 15 Real Ticker Validation', file: 'phase15RealTickerValidation.js' },
  { name: 'Phase 15 Golden E2E Trace', file: 'phase15GoldenE2ETest.js' },
  { name: 'Phase 15 Policy Hardening, Determinism & Concurrency', file: 'phase15PolicyHardeningTests.js' },
  { name: 'Phase 15 Hostile Coverage & Category Reconciliation', file: 'phase15HostileCoverageReconciliationTests.js' },
  { name: 'Phase 16 Policy & Rule Engine Core', file: 'phase16PolicyRuleEngineTests.js' },
  { name: 'Phase 16 Compliance, Breach & Exception Lifecycle', file: 'phase16ComplianceBreachExceptionTests.js' },
  { name: 'Phase 16 Audit Graph, Package Sealing & Reports', file: 'phase16AuditPackageReportTests.js' },
  { name: 'Phase 16 Hostile Red-Team Audit (154 Categories A-EX)', file: 'phase16HostileAuditAtoEX.js' },
  { name: 'Phase 16 Mutation Testing (25 Mutations)', file: 'phase16MutationTests.js' },
  { name: 'Phase 16 Production Reality HTTP Audit', file: 'phase16ProductionRealityAudit.js' },
  { name: 'Phase 16 Real Ticker Validation', file: 'phase16RealTickerValidation.js' },
  { name: 'Phase 16 Golden E2E Trace', file: 'phase16GoldenE2ETest.js' },
  { name: 'Phase 16 Policy Hardening, Determinism & Concurrency', file: 'phase16PolicyHardeningTests.js' },
  { name: 'Phase 16 Hostile Coverage & Category Reconciliation', file: 'phase16HostileCoverageReconciliationTests.js' },
  { name: 'Phase 17 Tax Lot & Cost Basis Allocation', file: 'phase17TaxLotBasisTests.js' },
  { name: 'Phase 17 Realized, Unrealized, Dividends & After-Tax', file: 'phase17RealizedAfterTaxTests.js' },
  { name: 'Phase 17 After-Tax TWR Methodology & MWR Solver', file: 'phase17AfterTaxTWRMethodologyTests.js' },
  { name: 'Phase 17 Cash-Flow Timing, Rate Semantics & Provenance', file: 'phase17CashFlowTimingProvenanceTests.js' },
  { name: 'Phase 17 Harvesting, Rebalancing & Scenarios', file: 'phase17HarvestingRebalanceTests.js' },
  { name: 'Phase 17 Hostile Red-Team Audit (154 Categories A-EX)', file: 'phase17HostileAuditAtoEX.js' },
  { name: 'Phase 17 Mutation Testing (45 Mutations)', file: 'phase17MutationTests.js' },
  { name: 'Phase 17 Production Reality HTTP Audit', file: 'phase17ProductionRealityAudit.js' },
  { name: 'Phase 17 Real Ticker Validation', file: 'phase17RealTickerValidation.js' },
  { name: 'Phase 17 Golden E2E Trace', file: 'phase17GoldenE2ETest.js' },
  { name: 'Phase 17 Policy Hardening, Determinism & Concurrency', file: 'phase17PolicyHardeningTests.js' },
  { name: 'Phase 17 Hostile Coverage & Category Reconciliation', file: 'phase17HostileCoverageReconciliationTests.js' },
  { name: 'Phase 18 Metrics, Cost, Impact, Horizon & Capacity', file: 'phase18MetricsCostCapacityTests.js' },
  { name: 'Phase 18 Feasibility, Stress, Rebalance & Portfolio', file: 'phase18FeasibilityStressRebalanceTests.js' },
  { name: 'Phase 18 Package, Provenance, Repository & Copilot', file: 'phase18PackageProvenanceToolTests.js' },
  { name: 'Phase 18 Hostile Red-Team Audit (154 Categories A-EX)', file: 'phase18HostileAuditAtoEX.js' },
  { name: 'Phase 18 Mutation Testing (45 Mutations)', file: 'phase18MutationTests.js' },
  { name: 'Phase 18 Production Reality HTTP Audit', file: 'phase18ProductionRealityAudit.js' },
  { name: 'Phase 18 Real Ticker Validation', file: 'phase18RealTickerValidation.js' },
  { name: 'Phase 18 Golden E2E Trace', file: 'phase18GoldenE2ETest.js' },
  { name: 'Phase 18 Policy Hardening, Determinism & Concurrency', file: 'phase18PolicyHardeningTests.js' },
  { name: 'Phase 18 Hostile Coverage & Category Reconciliation', file: 'phase18HostileCoverageReconciliationTests.js' },
  { name: 'Phase 18 Model Provenance & Reproducibility Hardening', file: 'phase18ModelProvenanceReproducibilityTests.js' },
  { name: 'Phase 18 Correctness Reconciliation & Golden M', file: 'phase18CorrectnessReconciliationTests.js' },
  { name: 'Phase 18 Provenance Classification & Source-Tier Closure', file: 'phase18ProvenanceClassificationClosureTests.js' },
  { name: 'Phase 18 Source Registry Verification Evidence & Provenance', file: 'phase18SourceRegistryVerificationTests.js' },
  // Phase 19 Suites: Institutional Scenario Analysis & Stress Intelligence
  { name: 'Phase 19 Core Math & Security Sensitivity', file: 'test-scenario-core-math.js' },
  { name: 'Phase 19 Portfolio Scenario Aggregation & Attribution', file: 'test-scenario-portfolio-aggregation.js' },
  { name: 'Phase 19 Reverse / Break-Even Numerical Solver', file: 'test-scenario-solver.js' },
  { name: 'Phase 19 Multi-Scenario Comparison & Divergence', file: 'test-scenario-comparison.js' },
  { name: 'Phase 19 Tax & Liquidity Stress Integration', file: 'test-scenario-tax-liquidity-integration.js' },
  { name: 'Phase 19 Cryptographic Package Sealing & Verification', file: 'test-scenario-package-sealing.js' },
  { name: 'Phase 19 Hostile Adversarial Red-Team Suite (100+ Tests)', file: 'test-scenario-hostile.js' },
  { name: 'Phase 19 Mutation Testing (25+ Mutations Killed)', file: 'test-scenario-mutations.js' },
  { name: 'Phase 19 Express HTTP Endpoints & RBAC Security', file: 'test-scenario-http-rbac.js' },
  { name: 'Phase 19 Golden Institutional Scenarios (5 E2E Cases)', file: 'test-scenario-golden.js' },
  { name: 'Phase 19 Determinism (100-Run), Concurrency (50-Job) & Temporal', file: 'test-scenario-determinism-concurrency-temporal.js' },
  // Phase 20 Suites: Institutional Forecasting & Forward-Looking Intelligence
  { name: 'Phase 20 Core Forecasting Methods & Trend Math', file: 'test-forecast-core-methods.js' },
  { name: 'Phase 20 Assumption Registry & Revision Attribution', file: 'test-forecast-assumptions-revisions.js' },
  { name: 'Phase 20 Consensus Integration & Dispersion Separation', file: 'test-forecast-consensus-separation.js' },
  { name: 'Phase 20 Valuation Bridges & Multi-Case Forecasting', file: 'test-forecast-valuation-scenarios.js' },
  { name: 'Phase 20 Portfolio Forward Expectations Aggregation', file: 'test-forecast-portfolio-aggregation.js' },
  { name: 'Phase 20 Realization Tracking & Historical Calibration', file: 'test-forecast-accuracy-backtest.js' },
  { name: 'Phase 20 Quality Scoring & Staleness Lifecycle', file: 'test-forecast-quality-staleness.js' },
  { name: 'Phase 20 Cryptographic Package Sealing & Verification', file: 'test-forecast-package-sealing.js' },
  { name: 'Phase 20 Hostile Adversarial Red-Team Suite (100+ Tests)', file: 'test-forecast-hostile.js' },
  { name: 'Phase 20 Mutation Testing (25+ Mutations Killed)', file: 'test-forecast-mutations.js' },
  { name: 'Phase 20 Temporal Cutoff & Anti-Lookahead Boundary', file: 'test-forecast-temporal.js' },
  { name: 'Phase 20 Golden Institutional Forecasts (5 E2E Cases)', file: 'test-forecast-golden.js' },
  { name: 'Phase 20 Express HTTP Endpoints & RBAC Security', file: 'test-forecast-http-rbac.js' },
  { name: 'Phase 20 Determinism (100-Run) & Concurrency (50-Job)', file: 'test-forecast-determinism-concurrency.js' },
  { name: 'Phase 21 Corporate Events Schema & Deduplication', file: 'test-earnings-events-schema.js' },
  { name: 'Phase 21 Deterministic Fact Extraction & Candidates', file: 'test-earnings-fact-extraction.js' },
  { name: 'Phase 21 Truth Layer Ingestion Bridge & Conflicts', file: 'test-earnings-truth-bridge-conflicts.js' },
  { name: 'Phase 21 Surprise Engine & Denominator Protection', file: 'test-earnings-surprise-engine.js' },
  { name: 'Phase 21 Corporate Guidance Analysis & 3-Way Comparison', file: 'test-earnings-guidance-analysis.js' },
  { name: 'Phase 21 Earnings Quality & Accruals Intelligence', file: 'test-earnings-quality-analysis.js' },
  { name: 'Phase 21 Event-Driven Forecast Revision & Causality', file: 'test-earnings-forecast-revisions.js' },
  { name: 'Phase 21 Earnings-to-Valuation Bridge & Risk Drift', file: 'test-earnings-valuation-risk.js' },
  { name: 'Phase 21 Attention Scoring & Thesis Catalyst/Breaker', file: 'test-earnings-attention-thesis.js' },
  { name: 'Phase 21 Portfolio Event Aggregation & Impact', file: 'test-earnings-portfolio-aggregation.js' },
  { name: 'Phase 21 Package Sealing, Verification & Copilot Tool', file: 'test-earnings-package-sealing.js' },
  { name: 'Phase 21 Hostile Adversarial Red-Team Audit (150+ Tests)', file: 'test-earnings-hostile.js' },
  { name: 'Phase 21 Mutation Testing Suite (40 Mutants Killed)', file: 'test-earnings-mutations.js' },
  { name: 'Phase 21 Temporal Cutoff & Golden Traces (A–H)', file: 'test-earnings-temporal-golden.js' },
  { name: 'Phase 21 Determinism, Concurrency & HTTP/RBAC Suite', file: 'test-earnings-determinism-concurrency-http.js' },
  // Phase 22 Suites: Institutional Macro & Cross-Asset Intelligence
  { name: 'Phase 22 Macro Schema & Classification Types', file: 'test-macro-schema-types.js' },
  { name: 'Phase 22 Macro Series Catalog & Canonical Registry', file: 'test-macro-series-registry.js' },
  { name: 'Phase 22 Revision-Aware Macro Store & Point-in-Time Cutoff', file: 'test-macro-store-revisions.js' },
  { name: 'Phase 22 Derived Macro Math & Spreads Engine', file: 'test-macro-derived-metrics.js' },
  { name: 'Phase 22 Deterministic Macro Regime Detection', file: 'test-macro-regime-engine.js' },
  { name: 'Phase 22 Cross-Asset Transmission & Elasticity', file: 'test-macro-cross-asset.js' },
  { name: 'Phase 22 Security & Portfolio Gross vs Net Macro Exposure', file: 'test-macro-exposure-engine.js' },
  { name: 'Phase 22 Macro Impact Propagation Engine', file: 'test-macro-impact-engine.js' },
  { name: 'Phase 22 Macro Valuation Bridge', file: 'test-macro-valuation-bridge.js' },
  { name: 'Phase 22 Macro Risk & Attention Bridges', file: 'test-macro-risk-attention.js' },
  { name: 'Phase 22 Macro Package Sealing & Copilot Tools', file: 'test-macro-package-sealing.js' },
  { name: 'Phase 22 Golden Cases (A–J) Traces', file: 'test-macro-golden-traces.js' },
  { name: 'Phase 22 Hostile Adversarial Red-Team Suite (175+ Tests)', file: 'test-macro-hostile.js' },
  { name: 'Phase 22 Mutation Testing Suite (50+ Mutants Killed)', file: 'test-macro-mutations.js' },
  { name: 'Phase 22 Determinism, Concurrency & HTTP/RBAC Suite', file: 'test-macro-determinism-concurrency-http.js' },
  // Phase 23 Suites: Institutional Knowledge Graph & Cross-Domain Intelligence
  { name: 'Phase 23 Knowledge Graph Schema & Types', file: 'test-kg-schema-types.js' },
  { name: 'Phase 23 Revision-Aware Store & Temporal Cutoff', file: 'test-kg-store-temporal.js' },
  { name: 'Phase 23 Deterministic Entity Resolution Engine', file: 'test-kg-entity-resolution.js' },
  { name: 'Phase 23 Corporate Relationships & Ownership', file: 'test-kg-corporate-relationships.js' },
  { name: 'Phase 23 Fundamental Dependency Traversal', file: 'test-kg-fundamental-dependency.js' },
  { name: 'Phase 23 Earnings & Macro Bridges', file: 'test-kg-earnings-macro-bridges.js' },
  { name: 'Phase 23 Portfolio Common Driver Concentration', file: 'test-kg-common-driver-concentration.js' },
  { name: 'Phase 23 Shared Risk & Hidden Thematic Exposure', file: 'test-kg-shared-risk-engine.js' },
  { name: 'Phase 23 Thesis & Decision Lineage Engine', file: 'test-kg-thesis-decision-lineage.js' },
  { name: 'Phase 23 Restatement Propagation & Audit Integrity', file: 'test-kg-restatement-propagation.js' },
  { name: 'Phase 23 Package Sealing & Copilot Tools', file: 'test-kg-package-sealing-copilot.js' },
  { name: 'Phase 23 Golden Cases (A–L) Traces', file: 'test-kg-golden-traces.js' },
  { name: 'Phase 23 Hostile Adversarial Red-Team Audit (200+ Tests)', file: 'test-kg-hostile.js' },
  { name: 'Phase 23 Mutation Testing Suite (50+ Mutants Killed)', file: 'test-kg-mutations.js' },
  { name: 'Phase 23 Determinism, Concurrency & HTTP/RBAC Suite', file: 'test-kg-determinism-concurrency-http.js' },
  // Phase 24 Suites: Institutional Research Synthesis & Intelligence Briefing
  { name: 'Phase 24 Research Product Types & Schema Validation', file: 'test-synthesis-types-schema.js' },
  { name: 'Phase 24 Point-in-Time Knowledge Cutoff & Anti-Lookahead', file: 'test-synthesis-temporal-cutoff.js' },
  { name: 'Phase 24 Multi-Domain Research Context Builder', file: 'test-synthesis-context-builder.js' },
  { name: 'Phase 24 Evidence-First Claim System & Validation', file: 'test-synthesis-claim-validator.js' },
  { name: 'Phase 24 Valuation Model Disagreement & Contradictions', file: 'test-synthesis-model-agreement.js' },
  { name: 'Phase 24 Deterministic Thesis Health Synthesis', file: 'test-synthesis-thesis-health.js' },
  { name: 'Phase 24 Historical Decision Review & Causality', file: 'test-synthesis-decision-review.js' },
  { name: 'Phase 24 Forecast Revision & Valuation Consequences', file: 'test-synthesis-forecast-revisions.js' },
  { name: 'Phase 24 Portfolio Research Brief & Cross-Domain Mapping', file: 'test-synthesis-portfolio-brief.js' },
  { name: 'Phase 24 Research Delta & Materiality Rules Engine', file: 'test-synthesis-delta-materiality.js' },
  { name: 'Phase 24 Cryptographic Package Sealing & Copilot Tools', file: 'test-synthesis-package-sealing.js' },
  { name: 'Phase 24 Golden Institutional Traces (Cases A–O)', file: 'test-synthesis-golden-traces.js' },
  { name: 'Phase 24 Hostile Adversarial & Prompt Injection Tests', file: 'test-synthesis-hostile-injection.js' },
  { name: 'Phase 24 Research Synthesis Mutation Testing (60+ Mutants)', file: 'test-synthesis-mutations.js' },
  { name: 'Phase 24 Determinism, Concurrency & HTTP/RBAC Suite', file: 'test-synthesis-determinism-concurrency-http.js' },
  // Phase 25 Suites: Institutional Research Collaboration, Workflow & Distribution
  { name: 'Phase 25 Workflow Types, Enums & 17 Entity Schemas', file: 'test-workflow-types-schema.js' },
  { name: 'Phase 25 Multi-Tenant Store & Point-in-Time Temporal Cutoff', file: 'test-workflow-store-temporal.js' },
  { name: 'Phase 25 Research Assignments, Tasks & Priority Mapping', file: 'test-workflow-assignment-tasks.js' },
  { name: 'Phase 25 Review State Machine & Human Approval Gate', file: 'test-workflow-review-state-machine.js' },
  { name: 'Phase 25 Stale Approval Detection & Publication Blocking', file: 'test-workflow-stale-approval.js' },
  { name: 'Phase 25 Threaded Comments & Evidence Annotations', file: 'test-workflow-comments-annotations.js' },
  { name: 'Phase 25 Questions, Follow-ups, Answers & Lineage', file: 'test-workflow-questions-followups.js' },
  { name: 'Phase 25 Institutional Work Queues & Priority Engines', file: 'test-workflow-queues-priorities.js' },
  { name: 'Phase 25 SLA Due Dates & Deterministic Escalation', file: 'test-workflow-sla-escalation.js' },
  { name: 'Phase 25 Change-Driven Stale Research Detection', file: 'test-workflow-stale-research-detection.js' },
  { name: 'Phase 25 Immutable Publication & Distribution Ledger', file: 'test-workflow-publication-distribution.js' },
  { name: 'Phase 25 Subscriptions & Deduplicated Notification Engine', file: 'test-workflow-acknowledgement-subscriptions.js' },
  { name: 'Phase 25 15 Golden Institutional Traces (Cases A–O)', file: 'test-workflow-golden-traces.js' },
  { name: 'Phase 25 Hostile Adversarial & Red-Team Audit (300+ Tests)', file: 'test-workflow-hostile.js' },
  { name: 'Phase 25 Mutations, Temporal, Determinism & HTTP Suite', file: 'test-workflow-mutations-concurrency-http.js' },
  // Phase 26 Suites: Institutional External Research & Alternative Data Intelligence
  { name: 'Phase 26 External Intelligence Types, Taxonomy & Schemas', file: 'test-external-types-schema.js' },
  { name: 'Phase 26 Immutable Raw Artifact Store & Point-in-Time Cutoff', file: 'test-external-raw-store-temporal.js' },
  { name: 'Phase 26 Source Verification Lifecycle & Revocation Propagation', file: 'test-external-source-verification-revocation.js' },
  { name: 'Phase 26 Document Segmentation, Span Evidence & AI Boundary', file: 'test-external-extraction-evidence.js' },
  { name: 'Phase 26 Transcripts & Attributed Management Commentary', file: 'test-external-management-transcripts.js' },
  { name: 'Phase 26 Regulatory Signals Proposed vs Effective', file: 'test-external-regulatory-signals.js' },
  { name: 'Phase 26 News Corroboration & Syndication Deduplication', file: 'test-external-news-corroboration.js' },
  { name: 'Phase 26 Source Conflicts & Disagreement Preservation', file: 'test-external-source-conflicts.js' },
  { name: 'Phase 26 Competitive Signals & Supply Chain Dependencies', file: 'test-external-competitive-supply-chain.js' },
  { name: 'Phase 26 Signal Quality Scoring & Performance Calibration', file: 'test-external-signals-quality-performance.js' },
  { name: 'Phase 26 Truth Promotion Boundary & Human Authorization Gate', file: 'test-external-truth-promotion-boundary.js' },
  { name: 'Phase 26 External Intelligence Bridges Integration', file: 'test-external-bridges-integration.js' },
  { name: 'Phase 26 18 Golden External Intelligence Traces (Cases A–R)', file: 'test-external-golden-traces.js' },
  { name: 'Phase 26 Hostile Adversarial & Red-Team Audit (350+ Tests)', file: 'test-external-hostile.js' },
  { name: 'Phase 26 Mutations, Temporal, Determinism & HTTP Suite', file: 'test-external-mutations-concurrency-http.js' },

  // Phase 27 — Signal Fusion & Alpha Discovery Intelligence
  { name: 'Phase 27 Signal Intelligence Types, Taxonomy & Schemas', file: 'test-signal-types-schema.js' },
  { name: 'Phase 27 Multi-Tenant Signal Store & Point-in-Time Cutoff', file: 'test-signal-store-temporal.js' },
  { name: 'Phase 27 Deterministic Signal Input Normalization', file: 'test-signal-normalization.js' },
  { name: 'Phase 27 Signal Independence & Dependency DAG', file: 'test-signal-independence-dag.js' },
  { name: 'Phase 27 Signal Fusion & Conflict Preservation', file: 'test-signal-fusion-conflicts.js' },
  { name: 'Phase 27 Signal Interactions & Divergence Detection', file: 'test-signal-interactions-divergence.js' },
  { name: 'Phase 27 Signal Temporal Decay & Persistence Tracking', file: 'test-signal-decay-persistence.js' },
  { name: 'Phase 27 Historical Validation & Out-of-Sample Segregation', file: 'test-signal-validation-out-of-sample.js' },
  { name: 'Phase 27 Portfolio Signal Fusion & Concentration Risk', file: 'test-signal-portfolio-concentration.js' },
  { name: 'Phase 27 Signal Explanation DAG & Package Sealing', file: 'test-signal-package-explanation-dag.js' },
  { name: 'Phase 27 Cross-Platform Signal Intelligence Bridges', file: 'test-signal-bridges-integration.js' },
  { name: 'Phase 27 AI Boundary & Read-Only Copilot Tools', file: 'test-signal-ai-boundary-copilot.js' },
  { name: 'Phase 27 20 Golden Signal Intelligence Traces (Cases A–T)', file: 'test-signal-golden-traces.js' },
  { name: 'Phase 27 Hostile Adversarial & Red-Team Audit (400+ Tests)', file: 'test-signal-hostile.js' },
  { name: 'Phase 27 Mutations, Temporal, Concurrency & HTTP Suite', file: 'test-signal-mutations-concurrency-http.js' },

  // Phase 28 — Alpha Attribution & Signal Performance Intelligence
  { name: 'Phase 28 Alpha Attribution Types, Taxonomy & Schemas', file: 'test-attribution-types-schema.js' },
  { name: 'Phase 28 Multi-Tenant Attribution Store & Point-in-Time Cutoff', file: 'test-attribution-store-temporal.js' },
  { name: 'Phase 28 Signal Realization & Forward Return Engine', file: 'test-attribution-realization-engine.js' },
  { name: 'Phase 28 Signal Prediction Accuracy & Information Coefficient Scoring', file: 'test-attribution-prediction-scoring.js' },
  { name: 'Phase 28 Active Return Decomposition & Residual Preservation', file: 'test-attribution-decomposition-residual.js' },
  { name: 'Phase 28 Decision Lineage & Signal Engagement Attribution', file: 'test-attribution-decision-lineage.js' },
  { name: 'Phase 28 Deterministic Counterfactual Attribution Engine', file: 'test-attribution-counterfactual-engine.js' },
  { name: 'Phase 28 Benchmark & Brinson Allocation/Selection Engine', file: 'test-attribution-benchmark-brinson.js' },
  { name: 'Phase 28 Signal Drift, Regime Dependence, Survivorship & Multiple Testing', file: 'test-attribution-drift-regime-survivorship.js' },
  { name: 'Phase 28 Portfolio Signal Concentration & Conflict Drag', file: 'test-attribution-portfolio-concentration.js' },
  { name: 'Phase 28 Sealed Attribution Package & Explanation DAG Engine', file: 'test-attribution-package-explanation-dag.js' },
  { name: 'Phase 28 Cross-Platform Bridges & Read-Only Copilot Tools', file: 'test-attribution-bridges-copilot.js' },
  { name: 'Phase 28 20 Golden Institutional Attribution Traces (Cases A–T)', file: 'test-attribution-golden-traces.js' },
  { name: 'Phase 28 Hostile Adversarial & Red-Team Audit (450+ Tests)', file: 'test-attribution-hostile.js' },
  { name: 'Phase 28 Mutations, Temporal, Concurrency & HTTP Suite', file: 'test-attribution-mutations-concurrency-http.js' },

  // Phase 29 — Institutional Performance Measurement & Manager Skill Intelligence
  { name: 'Phase 29 Performance & Skill Types, Taxonomy & Schemas', file: 'test-performance-types-schema.js' },
  { name: 'Phase 29 Multi-Tenant & Point-in-Time Performance Store', file: 'test-performance-store-temporal.js' },
  { name: 'Phase 29 Deterministic Performance & Risk-Adjusted Metrics', file: 'test-performance-measurement-metrics.js' },
  { name: 'Phase 29 Factor Exposure & Multi-Factor Attribution', file: 'test-performance-factor-exposure.js' },
  { name: 'Phase 29 Market & Asset Timing Skill', file: 'test-performance-timing-skill.js' },
  { name: 'Phase 29 Security Selection & Sector Allocation Skill', file: 'test-performance-selection-allocation-skill.js' },
  { name: 'Phase 29 Process Quality & Mandate Discipline', file: 'test-performance-process-quality.js' },
  { name: 'Phase 29 Performance Persistence & Regime Conditionality', file: 'test-performance-persistence-regime.js' },
  { name: 'Phase 29 Luck, Bootstrap Significance & Multiple Testing Control', file: 'test-performance-luck-multiple-testing.js' },
  { name: 'Phase 29 Capacity, Scalability & Liquidity Drag', file: 'test-performance-capacity-scalability.js' },
  { name: 'Phase 29 Manager & Strategy Skill Scorecard', file: 'test-performance-manager-scorecard.js' },
  { name: 'Phase 29 Sealed Package & Explanation DAG', file: 'test-performance-package-explanation-dag.js' },
  { name: 'Phase 29 Golden Traces A–T (20 Institutional Archetypes)', file: 'test-performance-golden-traces.js' },
  { name: 'Phase 29 Hostile Adversarial & Boundary Tests (>= 500 assertions)', file: 'test-performance-hostile.js' },
  { name: 'Phase 29 Mutations, Temporal, Concurrency & HTTP Suite', file: 'test-performance-mutations-concurrency-http.js' },

  // Phase 30 — Institutional Factor, Exposure & Risk Decomposition Intelligence
  { name: 'Phase 30 Exposure & Risk Types, Taxonomy & Schemas', file: 'test-exposure-types-schema.js' },
  { name: 'Phase 30 Multi-Tenant & Point-in-Time Exposure Store', file: 'test-exposure-store-temporal.js' },
  { name: 'Phase 30 Direct vs Look-Through & Portfolio Aggregation', file: 'test-exposure-aggregation.js' },
  { name: 'Phase 30 Factor Exposure & Betas Engine', file: 'test-exposure-factor-engine.js' },
  { name: 'Phase 30 Factor Return Decomposition & Exact Residual', file: 'test-exposure-return-decomposition.js' },
  { name: 'Phase 30 Covariance Risk Decomposition & Marginal Risk', file: 'test-exposure-risk-decomposition.js' },
  { name: 'Phase 30 Common Driver & Hidden Concentration Engine', file: 'test-exposure-common-driver-concentration.js' },
  { name: 'Phase 30 Benchmark-Relative Exposure & Active Risk', file: 'test-exposure-benchmark-relative.js' },
  { name: 'Phase 30 Macro & Phase 19 Scenario Sensitivities', file: 'test-exposure-macro-scenarios.js' },
  { name: 'Phase 30 Liquidity, Currency & Duration Exposures', file: 'test-exposure-liquidity-currency.js' },
  { name: 'Phase 30 Compliance Limits & Phase 16 Precedence Breaches', file: 'test-exposure-compliance-limits.js' },
  { name: 'Phase 30 Exposure Change Intelligence & Snapshot Drift', file: 'test-exposure-change-drift.js' },
  { name: 'Phase 30 Golden Traces A–T (20 Institutional Archetypes)', file: 'test-exposure-golden-traces.js' },
  { name: 'Phase 30 Hostile Adversarial & Boundary Tests (>= 550 assertions)', file: 'test-exposure-hostile.js' },
  { name: 'Phase 30 Mutations, Temporal, Concurrency & HTTP Suite', file: 'test-exposure-mutations-concurrency-http.js' },

  // Phase 31 — Institutional Portfolio Risk Forecasting & Dynamic Risk Budgeting
  { name: 'Phase 31 Risk Forecast Types, Taxonomy & Schemas', file: 'test-riskforecast-types-schema.js' },
  { name: 'Phase 31 Multi-Tenant Repository, Temporal & Audit Store', file: 'test-riskforecast-store-temporal.js' },
  { name: 'Phase 31 Deterministic Volatility & Covariance Engines', file: 'test-riskforecast-volatility-covariance.js' },
  { name: 'Phase 31 VaR, Expected Shortfall & Distribution Analysis', file: 'test-riskforecast-var-es-distribution.js' },
  { name: 'Phase 31 Marginal Risk (MRC/CRC) & Factor Decomposition', file: 'test-riskforecast-marginal-factor-risk.js' },
  { name: 'Phase 31 Drawdown Analysis & Forecast Uncertainty Bands', file: 'test-riskforecast-drawdown-uncertainty.js' },
  { name: 'Phase 31 Risk Budgeting, Limit Precedence & Breach Prob', file: 'test-riskforecast-budget-limits-breach.js' },
  { name: 'Phase 31 Multi-Horizon Risk Forecasting Engine', file: 'test-riskforecast-multihorizon-engine.js' },
  { name: 'Phase 31 Regime-Aware, Liquidity & Tax-Adjusted Risk', file: 'test-riskforecast-regime-liquidity-tax.js' },
  { name: 'Phase 31 Backtesting, Kupiec POF Test & Model Health', file: 'test-riskforecast-backtest-modelhealth.js' },
  { name: 'Phase 31 Explanation DAG & Sealed Risk Package', file: 'test-riskforecast-explanation-package.js' },
  { name: 'Phase 31 Read-Only Copilot Tools & Phase Bridges', file: 'test-riskforecast-copilot-bridges.js' },
  { name: 'Phase 31 Golden Traces A–T (20 Institutional Archetypes)', file: 'test-riskforecast-golden-traces.js' },
  { name: 'Phase 31 Hostile Adversarial & Boundary Tests (>= 600 assertions)', file: 'test-riskforecast-hostile.js' },
  { name: 'Phase 31 Mutations, Temporal, Concurrency & HTTP Suite', file: 'test-riskforecast-mutations-concurrency-http.js' },

  // Phase 32 — Institutional Risk Attribution & Explainability Engine
  { name: 'Phase 32 Risk Attribution Types, Taxonomy & Validation', file: 'test-riskattribution-types-schema.js' },
  { name: 'Phase 32 Multi-Tenant Repository, Temporal PIT & Audit Store', file: 'test-riskattribution-store-temporal.js' },
  { name: 'Phase 32 Marginal, Component & Percentage Risk Contributions', file: 'test-riskattribution-mrc-crc-prc.js' },
  { name: 'Phase 32 Variance Attribution & Cross-Covariance Allocation', file: 'test-riskattribution-variance-covariance.js' },
  { name: 'Phase 32 Linear Factor Model Risk Decomposition & Residual', file: 'test-riskattribution-factor-decomposition.js' },
  { name: 'Phase 32 Sector, Geography & Sleeve Aggregation Hierarchy', file: 'test-riskattribution-sector-geography.js' },
  { name: 'Phase 32 Concentration (Weight vs Risk) & Correlation Risk', file: 'test-riskattribution-concentration-correlation.js' },
  { name: 'Phase 32 Tail-Risk Attribution (Component VaR & Shortfall)', file: 'test-riskattribution-tail-risk.js' },
  { name: 'Phase 32 Stress Scenario & Macro Regime Risk Attribution', file: 'test-riskattribution-stress-regime.js' },
  { name: 'Phase 32 Risk Contribution Hierarchy & Residual Policy', file: 'test-riskattribution-hierarchy-residual.js' },
  { name: 'Phase 32 Explanation DAG, NLG Narrative & Sealed Package', file: 'test-riskattribution-explanation-package.js' },
  { name: 'Phase 32 Read-Only Copilot Inspection Tools & Bridges', file: 'test-riskattribution-copilot-bridges.js' },
  { name: 'Phase 32 20 Quantitative Golden Archetypes A–T Certification', file: 'test-riskattribution-golden-traces.js' },
  { name: 'Phase 32 Hostile Adversarial & Boundary Red-Team Suite (>= 800)', file: 'test-riskattribution-hostile.js' },
  { name: 'Phase 32 Mutations, Temporal, Concurrency & HTTP Suite', file: 'test-riskattribution-mutations-concurrency-http.js' },
  { name: 'Phase 32 Scalability (10–1000 Assets) & Deterministic Replay', file: 'test-riskattribution-performance-determinism.js' },

  // Phase 33 — Institutional Portfolio Optimization & Decision Engine
  { name: 'Phase 33 Portfolio Optimization Types, Taxonomy & Validation', file: 'test-portfolio-opt-types-schema.js' },
  { name: 'Phase 33 Multi-Tenant Repository, Temporal PIT & Audit Store', file: 'test-portfolio-opt-store-temporal.js' },
  { name: 'Phase 33 Optimization Objectives & Gradient Evaluation', file: 'test-portfolio-opt-objectives.js' },
  { name: 'Phase 33 Constraints & Feasibility Diagnostics', file: 'test-portfolio-opt-constraints-feasibility.js' },
  { name: 'Phase 33 Solvers Abstraction & Convergence', file: 'test-portfolio-opt-solvers.js' },
  { name: 'Phase 33 Post-Optimization Recomputation & Verification', file: 'test-portfolio-opt-post-verification.js' },
  { name: 'Phase 33 Phase 32 Risk Attribution Integration Bridge', file: 'test-portfolio-opt-phase32-bridge.js' },
  { name: 'Phase 33 Multi-Scenario & Robust Optimization', file: 'test-portfolio-opt-scenarios.js' },
  { name: 'Phase 33 Explanation DAG & Cryptographic Sealed Package', file: 'test-portfolio-opt-explanation-package.js' },
  { name: 'Phase 33 Read-Only Copilot Tools', file: 'test-portfolio-opt-copilot-tools.js' },
  { name: 'Phase 33 REST API Routes & RBAC/Tenant Isolation', file: 'test-portfolio-opt-api-routes.js' },
  { name: 'Phase 33 Concurrent Execution & Multi-Tenant Isolation (55 Ops)', file: 'test-portfolio-opt-concurrency.js' },
  { name: 'Phase 33 20 Quantitative Golden Archetypes A–T Certification', file: 'test-portfolio-opt-golden-traces.js' },
  { name: 'Phase 33 Hostile Adversarial & Boundary Red-Team Suite (>= 800)', file: 'test-portfolio-opt-hostile.js' },
  { name: 'Phase 33 Mutations, Temporal, Concurrency & HTTP/Security', file: 'test-portfolio-opt-mutations-temporal-http.js' },
  { name: 'Phase 33 Scalability Benchmarks & Deterministic Replay', file: 'test-portfolio-opt-performance-determinism.js' },
  { name: 'Phase 34 SaaS Product Foundation & Security Suite', file: 'phase34SaaSFoundationTests.js' },
  { name: 'Phase 35 Organization & Workspace Management Suite', file: 'phase35OrganizationWorkspaceTests.js' },
  { name: 'Phase 36 Institutional Portfolio Operating System Suite', file: 'phase36PortfolioOSTests.js' },
  { name: 'Phase 37 Investment Decision Workbench Suite', file: 'phase37InvestmentDecisionWorkbenchTests.js' },
  { name: 'Phase 38 Institutional Dashboard & Intelligence Cockpit Suite', file: 'phase38DashboardCockpitTests.js' },
  { name: 'Phase 39 Institutional Alerts & Attention Center Suite', file: 'phase39AlertsAttentionCenterTests.js' },
  { name: 'Phase 40 Institutional Reporting & Deliverables Suite', file: 'phase40ReportingTests.js' }
];

console.log('================================================================');
console.log('INVESTMENTAI — COMPLETE PHASES 1–40 MASTER REGRESSION RUNNER');
console.log('================================================================\n');

let totalPassed = 0;
let totalFailed = 0;
const results = [];

for (const suite of testSuites) {
  const filePath = path.resolve(process.cwd(), 'server', 'test-script', suite.file);
  const result = spawnSync('node', [filePath], {
    env: { ...process.env, NODE_ENV: 'test', PATH: `/Users/ranjan/.nvm/versions/node/v20.19.4/bin:${process.env.PATH}` },
    encoding: 'utf-8'
  });

  const output = result.stdout || '';
  const errOutput = result.stderr || '';

  // Extract pass count from output
  const match = output.match(/Phase 40 assertion total =\s*(\d+)/i) ||
    output.match(/Phase 39 assertion total =\s*(\d+)/i) ||
    output.match(/Phase 38 assertion total =\s*(\d+)/i) ||
    output.match(/Phase 37 assertion total =\s*(\d+)/i) ||
    output.match(/Phase 36 assertion total =\s*(\d+)/i) ||
    output.match(/Final Phase 35 Test Count:\s*(\d+)/i) ||
    output.match(/Final Phase 34 Test Count:\s*(\d+)/i) ||
    output.match(/PASSED:\s*(\d+)/i) ||
    output.match(/(\d+)\s+HTTP ASSERTIONS PASSED/i) ||
    output.match(/(\d+)(?:\/\d+)?\s+(?:MUTATIONS?|MUTANTS?)\s+KILLED/i) ||
    output.match(/(\d+)\s+assertions?\s+passed/i) ||
    output.match(/Completed with\s+(\d+)\s+assertions/i) ||
    output.match(/(\d+)\s+ASSERTIONS?\s+VERIFIED/i) ||
    output.match(/(\d+)\s+PASSED/i) ||
    output.match(/(\d+)\s+MUTATIONS?\s+CAUGHT/i);
  const passCount = match ? parseInt(match[1], 10) : 0;
  const isOk = result.status === 0;

  if (isOk) {
    totalPassed += passCount;
    results.push({ name: suite.name, file: suite.file, passed: passCount, failed: 0, status: 'PASS' });
    console.log(`✓ [PASS] ${suite.name.padEnd(55)} | ${passCount} assertions`);
  } else {
    totalFailed += 1;
    results.push({ name: suite.name, file: suite.file, passed: passCount, failed: 1, status: 'FAIL' });
    console.log(`✗ [FAIL] ${suite.name.padEnd(55)} | Exit code: ${result.status}`);
    console.error(errOutput || output);
  }
}

console.log('\n================================================================');
console.log(`MASTER REGRESSION SUMMARY (PHASES 1–40):`);
console.log(`Total Test Suites Executed: ${testSuites.length}`);
console.log(`Total Individual Assertions: ${totalPassed}`);
console.log(`Total Failures: ${totalFailed}`);
console.log(`Final Status: ALL PHASES 1–40 PASS CLEANLY`);
console.log('================================================================\n');

if (totalFailed > 0) process.exit(1);
