/**
 * Financial & Currency Formatting Utilities
 * Supports Indian Rupee (₹ Crores, ₹ Lakhs) and Global USD ($B, $M).
 */

export const formatCurrency = (value, currency = 'USD') => {
  if (value === null || value === undefined || isNaN(Number(value))) return 'N/A';
  
  const numValue = Number(value);
  const absVal = Math.abs(numValue);
  const isINR = (currency || '').toUpperCase() === 'INR';
  const symbol = isINR ? '₹' : '$';

  if (isINR) {
    // Indian Crore (1 Cr = 10,000,000) & Lakh (1 Lakh = 100,000)
    if (absVal >= 1e7) {
      return `${symbol}${(numValue / 1e7).toLocaleString('en-IN', { maximumFractionDigits: 2 })} Cr`;
    } else if (absVal >= 1e5) {
      return `${symbol}${(numValue / 1e5).toLocaleString('en-IN', { maximumFractionDigits: 2 })} Lakh`;
    } else {
      return `${symbol}${numValue.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
    }
  } else {
    // Western Trillion, Billion, Million
    if (absVal >= 1e12) {
      return `${symbol}${(numValue / 1e12).toFixed(2)}T`;
    } else if (absVal >= 1e9) {
      return `${symbol}${(numValue / 1e9).toFixed(2)}B`;
    } else if (absVal >= 1e6) {
      return `${symbol}${(numValue / 1e6).toFixed(2)}M`;
    } else {
      return `${symbol}${numValue.toLocaleString('en-US', { maximumFractionDigits: 2 })}`;
    }
  }
};

export const formatPercent = (value) => {
  if (value === null || value === undefined || isNaN(Number(value))) return 'N/A';
  let percentVal = Number(value);
  if (Math.abs(percentVal) < 1 && percentVal !== 0) {
    percentVal = percentVal * 100;
  }
  return `${percentVal >= 0 ? '+' : ''}${percentVal.toFixed(2)}%`;
};

export const formatRatio = (value) => {
  if (value === null || value === undefined || isNaN(Number(value))) return 'N/A';
  return `${Number(value).toFixed(2)}x`;
};

export const GLOSSARY = {
  peRatio: {
    title: 'Price-to-Earnings Ratio (P/E)',
    definition: 'A valuation ratio comparing a company\'s current share price to its per-share earnings (EPS).',
    formula: 'Share Price ÷ Earnings Per Share (EPS)',
    benchmark: 'Value: < 15x | Market Average: 20x–25x | High Growth: > 35x',
    category: 'Valuation'
  },
  operatingMargin: {
    title: 'Operating Profit Margin',
    definition: 'The percentage of revenue retained after paying production, labor, and operational costs before interest & taxes.',
    formula: '(Operating Income ÷ Total Revenue) × 100',
    benchmark: 'Healthy: > 15% | High Moat / Tech: > 25% | Capital Intensive: 8%–12%',
    category: 'Profitability'
  },
  netProfitMargin: {
    title: 'Net Profit Margin',
    definition: 'The percentage of total revenue remaining as net profit after all expenses, taxes, and interest deductions.',
    formula: '(Net Income ÷ Total Revenue) × 100',
    benchmark: 'Solid: > 10% | Outstanding: > 20% | Thin Margins: < 5%',
    category: 'Profitability'
  },
  freeCashFlow: {
    title: 'Free Cash Flow (FCF)',
    definition: 'Actual cash generated by core operations after subtracting capital expenditures (CapEx) needed to maintain or expand assets.',
    formula: 'Operating Cash Flow - Capital Expenditures (CapEx)',
    benchmark: 'Consistently positive and growing FCF enables share buybacks, dividends, and self-funded expansion.',
    category: 'Cash Flow'
  },
  roe: {
    title: 'Return on Equity (ROE)',
    definition: 'Measures management\'s efficiency at generating profits from every dollar/rupee of net assets owned by shareholders.',
    formula: '(Net Income ÷ Shareholder Equity) × 100',
    benchmark: 'Strong: > 15% | Elite Capital Allocators: > 25%',
    category: 'Efficiency'
  },
  roa: {
    title: 'Return on Assets (ROA)',
    definition: 'How efficiently a corporation deploys its total asset base (equipment, factories, cash) to generate bottom-line profit.',
    formula: '(Net Income ÷ Total Assets) × 100',
    benchmark: 'Good: > 5% | Outstanding: > 10%',
    category: 'Efficiency'
  },
  currentRatio: {
    title: 'Current Ratio (Liquidity)',
    definition: 'Measures a company\'s ability to pay off short-term obligations (due within 12 months) using short-term liquid assets.',
    formula: 'Total Current Assets ÷ Total Current Liabilities',
    benchmark: 'Safe: > 1.5x | Caution: 1.0x–1.3x | High Risk: < 1.0x',
    category: 'Solvency'
  },
  quickRatio: {
    title: 'Quick Ratio (Acid Test)',
    definition: 'An acid-test liquidity gauge excluding slow-moving inventory to verify immediate cash repayment capability.',
    formula: '(Cash + Marketable Securities + Receivables) ÷ Current Liabilities',
    benchmark: 'Safe: > 1.0x | Defensive: > 1.5x | Vulnerable: < 0.8x',
    category: 'Solvency'
  },
  beta: {
    title: 'Stock Beta (Market Volatility)',
    definition: 'Statistical measure of stock price volatility relative to the broader benchmark market index (S&P 500 / NIFTY 50).',
    formula: 'Covariance(Stock, Market) ÷ Variance(Market)',
    benchmark: 'Defensive: < 0.8 | Market Correlated: 1.0 | High Volatility: > 1.3',
    category: 'Risk'
  },
  dcf: {
    title: 'Discounted Cash Flow (DCF) Fair Value',
    definition: 'Intrinsic valuation methodology that discounts all projected 5-year future free cash flows back to today\'s value using WACC.',
    formula: 'Σ [ FCF_t ÷ (1 + WACC)^t ] + Terminal Value discounted to PV',
    benchmark: 'Market Price < Fair Value = Undervalued (Margin of Safety)',
    category: 'Intrinsic Valuation'
  },
  wacc: {
    title: 'WACC (Weighted Average Cost of Capital)',
    definition: 'The hurdle discount rate representing the blended expected return required by both debt holders and equity investors.',
    formula: '(E/V × Re) + (D/V × Rd × (1 - TaxRate))',
    benchmark: 'Large Cap Stable: 7.5%–9.0% | Mid/High Growth: 9.5%–12.5%',
    category: 'Discount Rate'
  },
  debtToCash: {
    title: 'Debt-to-Cash Multiple',
    definition: 'Direct comparison between total interest-bearing debt and liquid cash reserves on the balance sheet.',
    formula: 'Total Debt ÷ Total Cash & Short-Term Investments',
    benchmark: 'Pristine: < 1.0x (Net Cash Positive) | Moderate: 1.0x–2.5x | Leveraged: > 3.5x',
    category: 'Solvency'
  },
  eps: {
    title: 'Earnings Per Share (EPS TTM)',
    definition: 'The portion of a company\'s net profit allocated to each individual outstanding share of common stock over the trailing 12 months.',
    formula: '(Net Income - Preferred Dividends) ÷ Weighted Avg Shares Outstanding',
    benchmark: 'Consistent double-digit EPS growth drives long-term share price appreciation.',
    category: 'Profitability'
  },
  dividendYield: {
    title: 'Dividend Yield',
    definition: 'Annual dividend payouts expressed as a percentage of the current market share price.',
    formula: '(Annual Dividends Paid Per Share ÷ Current Stock Price) × 100',
    benchmark: 'Income Aristocrats: 3.0%–5.5% | Tech Growth: 0%–1.5%',
    category: 'Income'
  }
};

