/**
 * Change Engine Domain Types, Enums and Constants
 */

export const CHANGE_CATEGORIES = {
  PRICE: 'PRICE',
  REVENUE: 'REVENUE',
  EARNINGS: 'EARNINGS',
  FREE_CASH_FLOW: 'FREE_CASH_FLOW',
  MARGINS: 'MARGINS',
  DEBT: 'DEBT',
  CASH: 'CASH',
  LEVERAGE: 'LEVERAGE',
  LIQUIDITY: 'LIQUIDITY',
  VALUATION: 'VALUATION',
  RISK: 'RISK',
  BETA: 'BETA',
  VOLATILITY: 'VOLATILITY',
  RELATIVE_VALUATION: 'RELATIVE_VALUATION',
  REVERSE_DCF: 'REVERSE_DCF',
  CATALYST: 'CATALYST',
  THESIS: 'THESIS',
  THESIS_BREAKER: 'THESIS_BREAKER',
  DECISION: 'DECISION',
  DATA_QUALITY: 'DATA_QUALITY'
};

export const CHANGE_DIRECTIONS = {
  IMPROVING: 'IMPROVING',
  DETERIORATING: 'DETERIORATING',
  NEUTRAL: 'NEUTRAL',
  MIXED: 'MIXED',
  UNKNOWN: 'UNKNOWN'
};

export const MATERIALITY_LEVELS = {
  NEGLIGIBLE: 'NEGLIGIBLE',
  LOW: 'LOW',
  MATERIAL: 'MATERIAL',
  HIGHLY_MATERIAL: 'HIGHLY_MATERIAL',
  CRITICAL: 'CRITICAL'
};

export const THESIS_DRIFT_STATUS = {
  THESIS_STRENGTHENED: 'THESIS_STRENGTHENED',
  THESIS_WEAKENED: 'THESIS_WEAKENED',
  THESIS_UNCHANGED: 'THESIS_UNCHANGED',
  THESIS_MIXED: 'THESIS_MIXED',
  THESIS_INVALIDATED: 'THESIS_INVALIDATED',
  THESIS_RECOVERY: 'THESIS_RECOVERY'
};

export const BREAKER_MONITOR_STATUS = {
  NOT_TRIGGERED: 'NOT_TRIGGERED',
  APPROACHING: 'APPROACHING',
  TRIGGERED: 'TRIGGERED',
  RESOLVED: 'RESOLVED'
};

export const DECISION_HIERARCHY = {
  BUY: 4,
  HOLD: 3,
  WATCH: 2,
  AVOID: 1
};

export const RISK_LEVEL_HIERARCHY = {
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
  CRITICAL: 4,
  UNKNOWN: 0
};
