/**
 * Workspace Domain Types and Constants
 */

export const WORKSPACE_STATUS = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED'
};

export const WATCHLIST_STATUS = {
  ACTIVE: 'ACTIVE',
  MONITORING: 'MONITORING',
  ALERT: 'ALERT',
  PAUSED: 'PAUSED'
};

export const TIMELINE_EVENT_TYPES = {
  WORKSPACE_CREATED: 'WORKSPACE_CREATED',
  TICKER_ADDED: 'TICKER_ADDED',
  SNAPSHOT_CREATED: 'SNAPSHOT_CREATED',
  MATERIAL_CHANGE: 'MATERIAL_CHANGE',
  VALUATION_DRIFT: 'VALUATION_DRIFT',
  RISK_DRIFT: 'RISK_DRIFT',
  THESIS_DRIFT: 'THESIS_DRIFT',
  THESIS_BREAKER_APPROACHING: 'THESIS_BREAKER_APPROACHING',
  THESIS_BREAKER_TRIGGERED: 'THESIS_BREAKER_TRIGGERED',
  THESIS_BREAKER_RESOLVED: 'THESIS_BREAKER_RESOLVED',
  DECISION_TRANSITION: 'DECISION_TRANSITION',
  ALERT_TRIGGERED: 'ALERT_TRIGGERED',
  INTEGRITY_VIOLATION: 'INTEGRITY_VIOLATION'
};

export const EVENT_SEVERITY = {
  INFO: 'INFO',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};
